### ISSUE TITLE
能否写一个luci出来，那就非常完美了！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [cnsilvan/UnblockNeteaseMusic#1]
我也是悲催的K3！
1、烦请写一个适配的luci？
2、二进制文件放在哪个目录？是/usr/bin目录下吗？

**Comment by cnsilvan** [comment]
最近没空，有空了的时候如果还没人写，我就写。

**Comment by 1715173329** [comment]
https://github.com/project-openwrt/luci-app-unblockneteasemusic-go
