### ISSUE TITLE
ipad hd可用 iphone播放失败

### ISSUE THREAD

**Issue by neu-sunny** [cnsilvan/UnblockNeteaseMusic#10]
本人路由设备是斐讯K3，刷的OpenWrt，配套界面https://github.com/cnsilvan/luci-app-unblockneteasemusic

ios客户端已信任根证书
iPhone版本搜索歌曲后，原灰色歌曲显示正常，但播放时提示“网络不给力，无法继续播放”，iPad hd版本测试可用

本人小白，您的说明里提到的“ios客户端需要信任根证书且运行UnblockNeteaseMusic时 加上 -e 参数”
如何加上-e参数，麻烦帮解释一下，我在路由器上如何操作，谢谢了

**Comment by cnsilvan** [comment]
发一下路由器luci日志

**Comment by cnsilvan** [comment]
ios信任证书需要两次操作，第一次在描述文件，第二次在通用

**Comment by cnsilvan** [comment]
luci界面选择启用地址替换

**Comment by cnsilvan** [comment]
网易云版本是？

**Comment by neu-sunny** [comment]
> 发一下路由器luci日志

		##       ##         ##        ##   ##       ##       ## ##     ## ## ##      ## ## 
		##       ##       ## ##     ## ##  ##       ##    ##      ##      ##      ##      ##
		##       ##      ##  ##    ##  ##  ##       ##   ##               ##     ##
		##       ##     ##   ##   ##   ##  ##       ##    ## ## ##        ##     ##
		##       ##    ##    ##  ##    ##  ##       ##            ##      ##     ## 
		##       ##   ##     ## ##     ##  ##       ##  ##        ##      ##      ##      ##
		## ## ## ##  ##      ####      ##  ## ## ## ##   ## ## ##      ## ## ##    ## ## ##
		
                       0.1.3  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic） 

--------------------Config--------------------
port= 5210
tlsPort= 5211
source= kuwo:kugou:migu
certFile= /usr/share/UnblockNeteaseMusic/server.crt
keyFile= /usr/share/UnblockNeteaseMusic/server.key
mode= 0
-------------------Init Host-------------------
HostDomain: map[interface.music.163.com:101.71.154.241 music.163.com:59.111.181.60]
-------------------Init Proxy-------------------
starting Server  0.0.0.0:5210
starting TLS Server  0.0.0.0:5211
Transport:http://interface.music.163.com/api/sp/active/detect?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&deviceid=85ead0b610034e1938a8121bdac22a0f(interface.music.163.com)(HEAD)
Transport:http://interface.music.163.com/eapi/usersafe/pl/count(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/get(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/api/sp/active/detect?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&deviceid=85ead0b610034e1938a8121bdac22a0f(interface.music.163.com)(GET)
Direct:http://101.71.154.241/eapi/mlivestream/anchor/start-stream/entrance(interface.music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:51476: EOF
Transport:http://interface.music.163.com/eapi/event/user/permission(interface.music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:51478: EOF
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:51477: EOF
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:55005: EOF
Transport:http://interface.music.163.com/eapi/cloudvideo/category/list(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/pendant/user/get(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/user/pretend/info(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/delivery/batch-deliver(interface.music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:55008: EOF
Transport:http://interface.music.163.com/eapi/v1/user/detail/281130319(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/loading/current(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/act/playlist/vote/config(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/reward/artist/get(interface.music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:55010: EOF
Transport:http://interface.music.163.com/eapi/experiment/group/batch/get(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/webcache/reslist(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/pl/count(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music-vip-membership/client/vip/info(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/config/get(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/delivery/deliver(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/sub/artist/new/works/entrance(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/act/playlist/vote/config(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7(music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:55013: EOF
Transport:http://interface.music.163.com/eapi/pendant/user/get(interface.music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:55017: EOF
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/delivery/batch-deliver?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/delivery/deliver?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 11:56:35 http: TLS handshake error from 192.168.1.174:55018: EOF
2020/03/10 11:56:36 http: TLS handshake error from 192.168.1.174:55019: EOF
Transport:http://interface.music.163.com/eapi/ad/monitor/impress?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/hot/search/info/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/homepage/dragon/ball/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/banner/get/v3?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/homepage/block/page?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 11:56:36 http: TLS handshake error from 192.168.1.174:55022: EOF
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
2020/03/10 11:56:36 http: TLS handshake error from 192.168.1.174:55023: EOF
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
2020/03/10 11:56:36 http: TLS handshake error from 192.168.1.174:55033: EOF
2020/03/10 11:56:37 http: TLS handshake error from 192.168.1.174:55035: EOF
2020/03/10 11:56:37 http: TLS handshake error from 192.168.1.174:55037: EOF
2020/03/10 11:56:38 http: TLS handshake error from 192.168.1.174:55038: EOF
Transport:http://interface.music.163.com/eapi/search/specialkeyword/get?_nmclfl=1(interface.music.163.com)(POST)
Direct:http://101.71.154.241/eapi/mlivestream/interested/live/circle/check?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/commonconfig?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/store/eapi/entryconfig?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/api/sp/flow/status/v2?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&deviceid=85ead0b610034e1938a8121bdac22a0f&_nmclfl=1(interface.music.163.com)(GET)
Transport:http://interface.music.163.com/eapi/grayscale/version/info/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/nuser/follow/users/simple/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/config?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/loading/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/resniche/commontext/batch/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/v1/user/info?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/skin/thumbnail/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/store/eapi/webconfig?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/nmusician/artistread/info?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/cdns?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/share/encourage/config?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/blacklist/getOfficaId?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/toplist/default/pics/v2?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/comment/expression/list?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/user/setting?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/playlist/official/ids/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/appcustomconfig/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/event/user/setting?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/event/top/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/event/video/setting?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/comment/default/text?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/mlog/publish/config?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music-vbox/music/yun-ting/status?_nmclfl=1(interface.music.163.com)(POST)
Transport:https://interface.music.163.com/eapi/weixin/config?_nmclfl=1(interface.music.163.com)(POST)
Transport:https://interface.music.163.com/eapi/sp/flow/addr/v2?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/point/retrieve?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ios/version?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/matcher/audio/algorithm-code/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/user/grabed/status/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music/dislike/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/search/defaultkeyword/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/privilege?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music/dislike/change?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/mlog/songplay/entrance?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/zone/songplay/entry/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/player/url/v1?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/privilege?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/rncache/reslist?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/user/register/device?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/like/change?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music/dislike/get?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 11:56:39 http: TLS handshake error from 192.168.1.174:55041: EOF
find song info,id: 186005
Transport:https://music.163.com/eapi/resource/new/user/get?_nmclfl=1(music.163.com)(POST)
search song:搁浅 周杰伦
2020/03/10 11:56:39 http: TLS handshake error from 192.168.1.174:55042: EOF
Transport:https://music.163.com/eapi/resource/rcmd/daily/get?_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/search/rcmd/keyword/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/ad/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/lyric?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 11:56:40 http: TLS handshake error from 192.168.1.174:55043: EOF
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
consumed: 1173 ms
{"Id":"186005","Size":26215426,"Br":999000,"Url":"http://tyst.migu.cn/public/ringmaker01/n17/2017/07/%E6%97%A0%E6%8D%9F/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/flac/%E6%90%81%E6%B5%85-%E5%91%A8%E6%9D%B0%E4%BC%A6.flac","Md5":"","Name":"搁浅","Artist":"周杰伦","MatchScore":1}
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
2020/03/10 11:56:40 http: TLS handshake error from 192.168.1.174:55044: EOF
Transport:http://interface.music.163.com/eapi/ad/monitor/impress?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 11:56:41 http: TLS handshake error from 192.168.1.174:55046: EOF
Transport:http://interface.music.163.com/eapi/ad/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/v1/search/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
2020/03/10 11:56:41 http: TLS handshake error from 192.168.1.174:55047: EOF
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/v1/search/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/usersafe/pl/count?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/zone/songplay/entry/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/player/url/v1?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/feedback/weblog/fastlog?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/mlog/songplay/entrance?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=e7010aff6bbd3414e4ce84092083310353f5cb86c51470ace550556c76da5f17a80db9a1fdd86f1644f2c88da62884fffee47c8f26ba21c7&_nmclfl=1(music.163.com)(POST)
find song info,id: 186001
search song:七里香 周杰伦
Direct:http://101.71.154.241/eapi/mlivestream/entrance/playpage/v5/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/lyric?_nmclfl=1(interface.music.163.com)(POST)
consumed: 2828 ms
{"Id":"186001","Size":37169330,"Br":999000,"Url":"http://tyst.migu.cn/public/ringmaker01/n17/2017/07/%E6%97%A0%E6%8D%9F/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/flac/%E4%B8%83%E9%87%8C%E9%A6%99-%E5%91%A8%E6%9D%B0%E4%BC%A6.flac","Md5":"","Name":"七里香","Artist":"周杰伦","MatchScore":1}
2020/03/10 11:57:03 http: TLS handshake error from 192.168.1.174:55053: EOF
2020/03/10 11:57:03 http: TLS handshake error from 192.168.1.174:55054: EOF

**Comment by cnsilvan** [comment]
升级吧，都0.1.9了，另外发现ios设备APP 7.0.20及其以上的版本无法使用。有空排查。

**Comment by cnsilvan** [comment]
[0.2.0](https://github.com/cnsilvan/UnblockNeteaseMusic/releases/tag/0.2.0)已修复kugou，其他源正常
