### ISSUE TITLE
作者可以说说大体工作流程吗

### ISSUE THREAD

**Issue by lgf133214** [cnsilvan/UnblockNeteaseMusic#12]
目前golang版就这里有一个，最开始我想把你的源码翻一遍，自己再写一下，但发现想搞懂还是很困难的。现在改出来的也就将就可以跑，但要再深度的自定义就困难了。
所以，我希望作者可以出个稍微详细点的 go版本的翻译流程，起码让其他有兴趣的人有点参考，如果没时间，那也不勉强了🙏

**Comment by cnsilvan** [comment]
确实没时间
