### ISSUE TITLE
ios新版加-e也无法播放vip

### ISSUE THREAD

**Issue by paldier** [cnsilvan/UnblockNeteaseMusic#21]
~~看日志是找到的，但是无法播放~~
目前解锁vip出现问题，普通歌曲没有问题
如果改成https，
则使用-e时
ios正常
pc不正常
不使用-e时
ios不正常
pc正常
如果改成http，
则使用-e时
ios不正常
pc正常
不使用-e时
ios不正常
pc正常
`Transport:http://interface3.music.163.com/eapi/zone/songplay/entry/get?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/feedback/weblog/fastlog?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/content/exposure/songplay/entrance/animation?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/playlist/update/playcount?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/song/enhance/player/url/v1?_nmclfl=1(interface3.music.163.com)(POST)
find song info,id: 461518665
Transport:http://interface3.music.163.com/eapi/batch?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/content/exposure/songplay/entrance/ksong?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/usersafe/pl/count?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/music/songshare/text/recommend/get?_nmclfl=1(interface3.music.163.com)(POST)
Transport:http://interface3.music.163.com/eapi/batch?_nmclfl=1(interface3.music.163.com)(POST)
Direct:http://interface3.music.163.com/eapi/mlivestream/entrance/playpage/v5/get?_nmclfl=1(interface3.music.163.com)(POST)
search song:泣いちゃった(4人ver.) sympathy
Transport:http://interface3.music.163.com/eapi/song/lyric?_nmclfl=1(interface3.music.163.com)(POST)
consumed: 1385 ms
{"Id":"461518665","Size":18669151,"Br":999000,"Url":"http://ee.sycdn.kuwo.cn/715e53c96494624873e4ed64ae6bfaf8/5ef1ff4d/resource/s1/78/0/1374278854.flac","Md5":"","Name":"泣いちゃった","Artist":"sympathy","MatchScore":0.78571427}
2020/06/23 13:10:38 http: TLS handshake error from 192.168.50.95:59686: EOF
Direct:http://clientlog3.music.163.com/api/feedback/client/log?MUSIC_U=676e412b8971ecdf1323f1486a04dcd388146b7798635000bd7916870856193e1acb9679390a6b9cdf18dedd3c31fa0ecb6ab25aae854373c3061cd18d77b7a0&_nmclfl=1(clientlog3.music.163.com)(POST)
Direct:http://clientlog3.music.163.com/api/feedback/client/log?MUSIC_U=676e412b8971ecdf1323f1486a04dcd388146b7798635000bd7916870856193e1acb9679390a6b9cdf18dedd3c31fa0ecb6ab25aae854373c3061cd18d77b7a0&_nmclfl=1(clientlog3.music.163.com)(POST)
`

**Comment by paldier** [comment]
感觉只能使用https然后指定ios设备ip强制走https，这样就需要开两个进程，有点不完美

**Comment by cnsilvan** [comment]
> 感觉只能使用https然后指定ios设备ip强制走~https~-e，这样就需要开两个进程，而且还需要做ip匹配，有点不完美

其实header里面有设备信息的，有空的话弄个pr。我最近真的没空。

**Comment by cnsilvan** [comment]
#23 有人pr了
