### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ccssyybb** [cnsilvan/UnblockNeteaseMusic#22]
直接下的1.9M压缩版在华硕384路由不能运行。
$env:CGO_ENABLED=0
$env:GOOS="linux"
$env:GOARCH="arm"
$env:GOARM=5
$env:CC="arm-linux-gnueabi-gcc-4.7"
go build -o UNM -trimpath -ldflags "-s -w" ./app.go
自己尝试编译了下，二进制识别了，能启动了，网易云解锁了，就是无法播放歌曲，显示加载中。
后续再看看
是否编译有误

**Comment by ccssyybb** [comment]
用build.sh编译好的二进制arm.也不能生效。

**Comment by cnsilvan** [comment]
设备需要信任证书

**Comment by flyhigherpi** [comment]
> 设备需要信任证书

看到大佬连续更新了，测试下。
之前是安卓设备，用自己编译的，在梅林384机子上能识别版本号，运行，PC网易云显示加载中，安卓客户端一直转圈。
另一个二进制就能秒播放。均没有做过证书信任。
新版本的我测试下。
