### ISSUE TITLE
大佬，问一个处理机制的问题。

### ISSUE THREAD

**Issue by flyhigherpi** [cnsilvan/UnblockNeteaseMusic#25]
想法是本地路由运行网易云。然后通过clash配置一个127.0.0.1:5200的http节点，引流给unblockneteasemusic解锁。
实际使用中，发现无法解锁，引流成功的。
因为我尝试用GLOBAL模式，利用clash将流量都导入UN二进制，日志产生大量连接处理。
但疑惑的是，哪怕是163的流量进了UN，客户端并不能解锁。
----------------------------------------------
更新操作：
目前已经能摆脱iptable用clash运行了。
但是有新的问题出现：
UnblockNeteaseMusic -p 5200 -sp 5300 -m 0 -c /koolshare/bin/Music/server.crt -k /koolshare/bin/Music/server.key -e -b
一开始这样运行，流量进入二进制后没有处理，经人指点是缺少音源声明，改用
UnblockNeteaseMusic -p 5200 -sp 5300 -o kuwo:kugou -m 0 -c /koolshare/bin/Music/server.crt -k /koolshare/bin/Music/server.key -e -b
运行，PC能解锁，但是安卓手机客户端无法使用 （clash端是{name: 网易云解锁-本地, server: 127.0.0.1, port: 5200, type: http}）

现在尝试用
UnblockNeteaseMusic -p 5200 -sp 5300 -m 1 -c /koolshare/bin/Music/server.crt -k /koolshare/bin/Music/server.key -e -b
没有声明音源的情况下。手机端能显示全专辑解锁结果，比如周杰伦；但是PC端又无法显示专辑解锁！！！
clash 端是{name: 网易云解锁-本地, server: 0.0.0.0, port: 5200, type: http}
而且UnblockNeteaseMusic -p 5200 -sp 5300 -m 0 -c /koolshare/bin/Music/server.crt -k /koolshare/bin/Music/server.key -e -b
-m 0 的情况下。无法启动。

**Comment by flyhigherpi** [comment]
补充，而如果是PC客户端设置了192.168.2.1:5200的http代理，就会产生属于网易云解锁的日志内容。

**Comment by flyhigherpi** [comment]
折腾来折腾去，发现还是iptable用ipset透明代理效率高。放弃用clash分流解锁了。关了关了。

**Comment by LittleRey** [comment]
@flyhigherpi 问，我在本地运行unblock,无法解锁，问怎么解决的
