### ISSUE TITLE
[Bug Report] accept4: too many open files

### ISSUE THREAD

**Issue by Zxilly** [cnsilvan/UnblockNeteaseMusic#27]
![image](https://user-images.githubusercontent.com/31370133/89368038-21cf4580-d70d-11ea-9e3f-99c04db9b3b6.png)
是否忘记关闭开启的连接了？

**Comment by cnsilvan** [comment]
目前没有人反应这个问题，需要提供你的使用环境，你是提供很多人使用了？建议提高 file-max limit ，或者用nginx来代理。

**Comment by Zxilly** [comment]
file limit是65535，只有我自己使用，基本上一首歌就会出现这个问题，然后重启能够暂时解决

**Comment by Zxilly** [comment]
也许是被渗透攻击扫了？

**Comment by cnsilvan** [comment]
检查一下吧
