### ISSUE TITLE
0.24 mipsle-softfloat 无法启动 pac问题

### ISSUE THREAD

**Issue by agkyunromb** [cnsilvan/UnblockNeteaseMusic#28]
旁路由 NEW-WIFI D2（MT7621A pandvan固件）
UnblockNeteaseMusic -p 2333 -sp 2334 -e -m 2 -b
0.24 mipsle-softfloat 会直接卡住，而0.23版可以运行
然后不知道为什么pac模式Linux ios 都不能使用了
可以访问 http://192.168.123.2:2333/proxy.pac 只显示版本号和logo
日志里一直报  Abandon:http://192.168.123.2:2333/proxy.pac

**Comment by cnsilvan** [comment]
尝试自己打包试一试，可能是upx3.96 对mipsle支持不够好。我下次发布前降级3.95
