### ISSUE TITLE
请教一下windows下要如何生成自己的证书？？？

### ISSUE THREAD

**Issue by caliban511** [cnsilvan/UnblockNeteaseMusic#29]
如题。
在路由器上启用后，Windows下的页面显示变成这样：
https://github.com/maxlicheng/luci-app-unblockmusic/issues/140

看来看去，貌似就是证书过期了，，，
请教一下，应该怎么弄？

**Comment by cnsilvan** [comment]
我的luci是有证书删除功能的，可以删除了然后重启，会自动生成新的证书。然后下载下来信任即可。

**Comment by caliban511** [comment]
> 
> 
> 我的[luci](https://github.com/cnsilvan/luci-app-unblockneteasemusic)是有证书删除功能的，可以删除了然后重启，会自动生成新的证书。然后下载下来信任即可。

感谢大佬回复，但你这个太高级了，完全不知道要怎么用。
我下载了UnblockNeteaseMusic-linux-amd64.zip这个包后，到处找用法找不到，试着把它解压扔到/usr/bin目录下，但你的这个luci仍然安装不上。
希望能给个用法说明，谢谢大佬。
![snipaste_20200910_185328](https://user-images.githubusercontent.com/13557387/92720574-5df26780-f397-11ea-8ca5-87caad6da895.jpg)

**Comment by caliban511** [comment]
> 
> 
> 我的[luci](https://github.com/cnsilvan/luci-app-unblockneteasemusic)是有证书删除功能的，可以删除了然后重启，会自动生成新的证书。然后下载下来信任即可。

大佬你好，因为不会用你的文件，就又装回之前的那个ipk，然后手动删掉浏览器里过期的CA，然后重新下载，导入，信任。
现在浏览器可以进入页面了，但有的歌曲还是不能播放，播放按钮是灰色，这正常吗？
还是说这个插件只能用于客户端？浏览器用不了？
![snipaste_20200910_192154](https://user-images.githubusercontent.com/13557387/92723149-3bfae400-f39b-11ea-9b49-2dfdb362877f.jpg)

**Comment by cnsilvan** [comment]
> > 我的[luci](https://github.com/cnsilvan/luci-app-unblockneteasemusic)是有证书删除功能的，可以删除了然后重启，会自动生成新的证书。然后下载下来信任即可。
> 
> 大佬你好，因为不会用你的文件，就又装回之前的那个ipk，然后手动删掉浏览器里过期的CA，然后重新下载，导入，信任。
> 现在浏览器可以进入页面了，但有的歌曲还是不能播放，播放按钮是灰色，这正常吗？
> 还是说这个插件只能用于客户端？浏览器用不了？
> ![snipaste_20200910_192154](https://user-images.githubusercontent.com/13557387/92723149-3bfae400-f39b-11ea-9b49-2dfdb362877f.jpg)

网页一直在更新，和客户端有所不同。没时间去适配。
