### ISSUE TITLE
开了ipv6会导致IOS解锁失败？

### ISSUE THREAD

**Issue by dgyangxf** [cnsilvan/UnblockNeteaseMusic#32]
我用ACRH17，联通pppoe，lintel的潘多拉1902，默认自动获取ipv6，但是必须关闭ipv6才能解锁。ios14，关闭ipv6后可以不用设置代理就能解锁

**Comment by cnsilvan** [comment]
> 我用ACRH17，联通pppoe，lintel的潘多拉1902，默认自动获取ipv6，但是必须关闭ipv6才能解锁。ios14，关闭ipv6后可以不用设置代理就能解锁
你用的什么LUCI插件？

**Comment by dgyangxf** [comment]
也是用你的这个Luci
https://github.com/cnsilvan/luci-app-unblockneteasemusic

**Comment by cnsilvan** [comment]
> 也是用你的这个Luci
> https://github.com/cnsilvan/luci-app-unblockneteasemusic


你需要检查一下是否禁止了解析 IPv6 DNS 记录。
如果需要使用ipv6 需要openwrt 开启ipv6  dns 记录 并重启插件
