### ISSUE TITLE
所有app已经不能实现全部解锁了

### ISSUE THREAD

**Issue by paldier** [cnsilvan/UnblockNeteaseMusic#35]
`2020/12/28 11:49:42 --------------------Config--------------------
2020/12/28 11:49:42 port= 5200
2020/12/28 11:49:42 tlsPort= 5300
2020/12/28 11:49:42 source= kuwo
2020/12/28 11:49:42 certFile= /jffs/softcenter/bin/Music/server.crt
2020/12/28 11:49:42 keyFile= /jffs/softcenter/bin/Music/server.key
2020/12/28 11:49:42 logFile= /tmp/unblockmusic.log
2020/12/28 11:49:42 mode= 0
2020/12/28 11:49:42 endPoint= true
2020/12/28 11:49:42 forceBestQuality= false
2020/12/28 11:49:42 searchLimit= 2
2020/12/28 11:49:42 -------------------Init Host-------------------
2020/12/28 11:49:42 HostDomain: map[interface.music.163.com:112.13.119.17 music.163.com:59.111.181.35]
2020/12/28 11:49:42 -------------------Init Proxy-------------------
2020/12/28 11:49:42 Http Proxy:
2020/12/28 11:49:42 192.168.1.2 , 192.168.51.1
2020/12/28 11:49:42 starting Server  0.0.0.0:5200
2020/12/28 11:49:42 starting TLS Server  0.0.0.0:5300
2020/12/30 08:29:45 Transport:http://music.163.com/api/w/user/login/type/switch(music.163.com)(POST)
2020/12/30 08:29:45 Local Received request CONNECT music.163.com 192.168.51.159:62859
2020/12/30 08:29:45 Transport:http://music.163.com/api/blacklist/getOfficaId(music.163.com)(POST)
2020/12/30 08:29:45 Transport:http://music.163.com/eapi/appcustomconfig/get(music.163.com)(POST)
2020/12/30 08:29:45 Transport:http://music.163.com/eapi/batch(music.163.com)(POST)
2020/12/30 08:29:45 Transport:http://music.163.com/eapi/abtest/group/get(music.163.com)(POST)
2020/12/30 08:29:46 Local Received request CONNECT music.163.com 192.168.51.159:62863
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/ad/get(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/event/user/permission(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/usertool/sound/mobile/whalecloudnewadd(music.163.com)(POST)
2020/12/30 08:29:46 Local Received request CONNECT music.163.com 192.168.51.159:62864
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/usertool/sound/mobile/whalecloudnewadd(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/batch(music.163.com)(POST)
2020/12/30 08:29:46 Local Received request CONNECT music.163.com 192.168.51.159:62865
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/user/playlist/(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/delivery/deliver(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/privacy/info/get/v2(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/point/retrieve(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/v1/cloud/get(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://music.163.com/eapi/pl/count(music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://interface.music.163.com/eapi/batch(interface.music.163.com)(POST)
2020/12/30 08:29:46 Transport:http://interface.music.163.com/eapi/push/init(interface.music.163.com)(POST)
2020/12/30 08:29:47 Direct:http://112.13.119.17/eapi/mlivestream/entrance/playpage/get(interface.music.163.com)(POST)
2020/12/30 08:29:47 Transport:http://interface.music.163.com/eapi/v6/playlist/detail(interface.music.163.com)(POST)
2020/12/30 08:29:47 Transport:http://interface.music.163.com/eapi/user/getfollows/3220475134(interface.music.163.com)(POST)
2020/12/30 08:29:47 Received request CONNECT p3.music.126.net 192.168.51.159:62874
2020/12/30 08:29:47 Received request CONNECT p4.music.126.net 192.168.51.159:62876
2020/12/30 08:29:47 Received request CONNECT p4.music.126.net 192.168.51.159:62875
2020/12/30 08:29:47 Received request CONNECT p4.music.126.net 192.168.51.159:62877
2020/12/30 08:29:47 Received request CONNECT p4.music.126.net 192.168.51.159:62878
2020/12/30 08:29:47 Received request CONNECT p1.music.126.net 192.168.51.159:62881
2020/12/30 08:29:47 Received request CONNECT p1.music.126.net 192.168.51.159:62879
2020/12/30 08:29:47 Received request CONNECT p1.music.126.net 192.168.51.159:62880
2020/12/30 08:29:47 Received request CONNECT p1.music.126.net 192.168.51.159:62883
2020/12/30 08:29:47 Received request CONNECT p1.music.126.net 192.168.51.159:62882
2020/12/30 08:29:47 Transport:http://interface.music.163.com/eapi/batch(interface.music.163.com)(POST)
2020/12/30 08:29:48 Received request CONNECT p1.music.126.net 192.168.51.159:62884
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/pc/upgrade/get(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/cdns(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/song/lyric(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/batch(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/vipcenter/tspopup/get(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/vipcenter/app/vipconfig/get(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/copyright/pay_fee_message/config(interface.music.163.com)(POST)
2020/12/30 08:29:48 Direct:http://web.push.126.net:6003/socket.io/1/?t=1609316988243(web.push.126.net)(GET)
2020/12/30 08:29:48 Local Received request CONNECT interface.music.163.com 192.168.51.159:62891
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/w/v1/user/bindings/3220475134(interface.music.163.com)(POST)
2020/12/30 08:29:48 Transport:http://interface.music.163.com/eapi/v6/playlist/detail(interface.music.163.com)(POST)
2020/12/30 08:29:48 Local Received request CONNECT interface.music.163.com 192.168.51.159:62892
2020/12/30 08:29:48 Received request CONNECT p3.music.126.net 192.168.51.159:62893
2020/12/30 08:29:48 Received request CONNECT p3.music.126.net 192.168.51.159:62894
2020/12/30 08:29:48 Received request CONNECT p3.music.126.net 192.168.51.159:62896
2020/12/30 08:29:48 Received request CONNECT p3.music.126.net 192.168.51.159:62895
2020/12/30 08:29:48 Received request CONNECT p2.music.126.net 192.168.51.159:62898
2020/12/30 08:29:48 Received request CONNECT p3.music.126.net 192.168.51.159:62897
2020/12/30 08:29:48 Local Received request CONNECT interface.music.163.com 192.168.51.159:62899
2020/12/30 08:29:48 Received request CONNECT p2.music.126.net 192.168.51.159:62900
2020/12/30 08:29:49 Received request CONNECT web.push.126.net 192.168.51.159:62901
2020/12/30 08:29:49 Received request CONNECT p2.music.126.net 192.168.51.159:62902
2020/12/30 08:29:49 Transport:http://interface.music.163.com/eapi/login/token/refresh(interface.music.163.com)(POST)
2020/12/30 08:29:49 Received request CONNECT p2.music.126.net 192.168.51.159:62904
2020/12/30 08:29:49 Local Received request CONNECT interface.music.163.com 192.168.51.159:62903
2020/12/30 08:29:49 Transport:http://interface.music.163.com/eapi/v3/song/detail(interface.music.163.com)(POST)
2020/12/30 08:29:49 Received request CONNECT p2.music.126.net 192.168.51.159:62905
2020/12/30 08:29:49 Received request CONNECT p2.music.126.net 192.168.51.159:62906
2020/12/30 08:29:49 Transport:http://interface.music.163.com/eapi/pc/upgrade/get(interface.music.163.com)(POST)
2020/12/30 08:29:50 Direct:http://clientlog.music.163.com/api/feedback/client/log(clientlog.music.163.com)(POST)
2020/12/30 08:29:50 Transport:http://interface.music.163.com/eapi/v3/song/detail(interface.music.163.com)(POST)
2020/12/30 08:29:51 Transport:http://interface.music.163.com/eapi/user/playlist/(interface.music.163.com)(POST)
2020/12/30 08:29:51 Transport:http://interface.music.163.com/eapi/v3/song/detail(interface.music.163.com)(POST)
2020/12/30 08:29:53 Transport:http://interface.music.163.com/eapi/v3/song/detail(interface.music.163.com)(POST)
2020/12/30 08:29:54 Transport:http://interface.music.163.com/eapi/v3/song/detail(interface.music.163.com)(POST)
2020/12/30 08:29:54 Transport:http://interface.music.163.com/eapi/ad/monitor/impress(interface.music.163.com)(POST)
2020/12/30 08:29:55 Transport:http://interface.music.163.com/eapi/login/token/refresh(interface.music.163.com)(POST)
2020/12/30 08:30:01 Transport:http://interface.music.163.com/eapi/resource-exposure/config(interface.music.163.com)(POST)
2020/12/30 08:30:01 Transport:http://interface.music.163.com/eapi/v6/playlist/detail(interface.music.163.com)(POST)
2020/12/30 08:30:01 Direct:http://112.13.119.17/eapi/mlivestream/entrance/playlist/get(interface.music.163.com)(POST)
2020/12/30 08:30:02 Transport:http://interface.music.163.com/eapi/resource-exposure/config(interface.music.163.com)(POST)
2020/12/30 08:30:07 Received request CONNECT ac.dun.163yun.com 192.168.51.159:62943
2020/12/30 08:30:08 Transport:http://interface.music.163.com/eapi/playlist/update/playcount(interface.music.163.com)(POST)
2020/12/30 08:30:08 Transport:http://interface.music.163.com/eapi/song/enhance/player/url(interface.music.163.com)(POST)
2020/12/30 08:30:08 Direct:http://112.13.119.17/eapi/mlivestream/entrance/playpage/get(interface.music.163.com)(POST)
2020/12/30 08:30:09 find song info :{Quality:ExHigh(2) Id:437856507}
2020/12/30 08:30:09 Transport:http://interface.music.163.com/eapi/song/lyric(interface.music.163.com)(POST)
2020/12/30 08:30:12 search song:魔法陣より愛を込めて カラスは真っ白
2020/12/30 08:30:12 consumed: 482 ms
2020/12/30 08:30:12 {"Id":"437856507","Size":0,"Br":0,"Url":"","Md5":"","Name":"","Artist":"","AlbumName":"","MatchScore":0,"Source":""}
2020/12/30 08:30:12 Transport:http://interface.music.163.com/eapi/song/enhance/player/url(interface.music.163.com)(POST)
2020/12/30 08:30:12 Direct:http://112.13.119.17/eapi/mlivestream/entrance/playpage/get(interface.music.163.com)(POST)
2020/12/30 08:30:12 Transport:http://interface.music.163.com/eapi/song/lyric(interface.music.163.com)(POST)
2020/12/30 08:30:13 Received request CONNECT m8.music.126.net 192.168.51.159:62954
`
无论是自动代理还是手动指定代理都已经无法解锁，预计以后也不能解决了，留个log

**Comment by paldier** [comment]
`https://httpdns.n.netease.com/httpdns/v2/s?session_id=1609318327988_18467`
第一条链接信息就是app在获取ip，预防写host？

**Comment by paldier** [comment]
`2020/12/30 09:04:15 Direct:https://httpdns.n.netease.com/httpdns/v2/d?session_id=1609319054779_15955&domain=clientlog.music.163.com,interface.music.163.com,m7.music.126.net,m701.music.126.net,m8.music.126.net,m801.music.126.net,m9.music.126.net,music.163.com,p1.music.126.net,p2.music.126.net,p3.music.126.net,p4.music.126.net,p5.music.126.net,p6.music.126.net,vodkgeyttp8.vod.126.net,vodkgeyttp9.vod.126.net(httpdns.n.netease.com)(GET)`
期间会多次获取ip

**Comment by paldier** [comment]
`2020/12/30 09:11:17 http.Client.Do fail:Get http://www.kuwo.cn/api/www/search/searchMusicBykeyWord?key=POSE+%E8%BE%BB%E8%A9%A9%E9%9F%B3&pn=1&rn=30: dial tcp: i/o timeout
2020/12/30 09:11:17 Get http://www.kuwo.cn/api/www/search/searchMusicBykeyWord?key=POSE+%E8%BE%BB%E8%A9%A9%E9%9F%B3&pn=1&rn=30: dial tcp: i/o timeout`
403

**Comment by EnzoTools** [comment]
> `2020/12/30 09:11:17 http.Client.Do fail:Get http://www.kuwo.cn/api/www/search/searchMusicBykeyWord?key=POSE+%E8%BE%BB%E8%A9%A9%E9%9F%B3&pn=1&rn=30: dial tcp: i/o timeout 2020/12/30 09:11:17 Get http://www.kuwo.cn/api/www/search/searchMusicBykeyWord?key=POSE+%E8%BE%BB%E8%A9%A9%E9%9F%B3&pn=1&rn=30: dial tcp: i/o timeout`
> 403

我也遇到了相同的问题 ;(

**Comment by cnsilvan** [comment]
> `2020/12/30 09:04:15 Direct:https://httpdns.n.netease.com/httpdns/v2/d?session_id=1609319054779_15955&domain=clientlog.music.163.com,interface.music.163.com,m7.music.126.net,m701.music.126.net,m8.music.126.net,m801.music.126.net,m9.music.126.net,music.163.com,p1.music.126.net,p2.music.126.net,p3.music.126.net,p4.music.126.net,p5.music.126.net,p6.music.126.net,vodkgeyttp8.vod.126.net,vodkgeyttp9.vod.126.net(httpdns.n.netease.com)(GET)`
> 期间会多次获取ip
未发现封锁，估摸着你们请求次数太多？是否拿来做服务器了？

**Comment by paldier** [comment]
现在新旧版都一样的，只能部分解锁，而那部分可以解锁的就是代理了126之后才解锁的，所以可能是屏蔽了使用其他源？

**Comment by cnsilvan** [comment]
> 现在新旧版都一样的，只能部分解锁，而那部分可以解锁的就是代理了126之后才解锁的，所以可能是屏蔽了使用其他源？

我的设备一切正常。

**Comment by cnsilvan** [comment]
> 现在新旧版都一样的，只能部分解锁，而那部分可以解锁的就是代理了126之后才解锁的，所以可能是屏蔽了使用其他源？

你提供一下你的使用环境。包括核心配置。
