### ISSUE TITLE
想问下怎样下载非网易云平台音乐呢

### ISSUE THREAD

**Issue by pipixia244** [cnsilvan/UnblockNeteaseMusic#36]
![image](https://user-images.githubusercontent.com/56287117/104817071-ea3afc80-5859-11eb-8dcd-2f43c73f33f8.png)
比如上图，我想下载这个来自酷我音乐的歌曲，但是点击下载会让我添加到歌单，然后我选择任意歌单后出现这个错误
![image](https://user-images.githubusercontent.com/56287117/104817089-0343ad80-585a-11eb-8f55-8ecc3d38fa5f.png)
有办法下载这种非网易云平台的音乐吗？

**Comment by cnsilvan** [comment]
三方平台无法收藏。你可以找找后几页是否有网易云同名的资源。三方资源最好只拿来用作网易云资源的补充。
