### ISSUE TITLE
尝试搭建了个heroku，无法使用，利用caddy反代了流量，但是还是没有用

### ISSUE THREAD

**Issue by LittleRey** [cnsilvan/UnblockNeteaseMusic#38]
https://github.com/LittleRey/heroku-UnblockNeteaseMusic
能不能看一看

**Comment by cnsilvan** [comment]
> https://github.com/LittleRey/heroku-UnblockNeteaseMusic
> 能不能看一看

实在没空哈，不管你利用什么，首要排除配置是否正确。
