### ISSUE TITLE
提示 tls: unknown certificate

### ISSUE THREAD

**Issue by phoenixxie7** [cnsilvan/UnblockNeteaseMusic#39]
安卓端打开网易云之后，搜索周董的歌。路由器服务端日志显示
‘
2021/01/30 22:13:01 --------------------Config--------------------
2021/01/30 22:13:01 port= 5210
2021/01/30 22:13:01 tlsPort= 5211
2021/01/30 22:13:01 source= kuwo
2021/01/30 22:13:01 certFile= /usr/share/UnblockNeteaseMusic/server.crt
2021/01/30 22:13:01 keyFile= /usr/share/UnblockNeteaseMusic/server.key
2021/01/30 22:13:01 logFile= /tmp/unblockneteasemusic.log
2021/01/30 22:13:01 mode= 0
2021/01/30 22:13:01 endPoint= true
2021/01/30 22:13:01 forceBestQuality= false
2021/01/30 22:13:01 searchLimit= 0
2021/01/30 22:13:01 -------------------Init Host-------------------
ping6 bad address,please check IPv6 DNS forwards.if IPv6 DNS forwards is enabled, please restart
2021/01/30 22:13:02 HostDomain: map[interface.music.163.com:115.236.118.33 music.163.com:59.111.181.38]
2021/01/30 22:13:02 -------------------Init Proxy-------------------
2021/01/30 22:13:02 Http Proxy:
2021/01/30 22:13:02 IP地址隐藏
2021/01/30 22:13:02 starting Server  0.0.0.0:5210
2021/01/30 22:13:02 starting TLS Server  0.0.0.0:5211
2021/01/30 22:13:09 http: TLS handshake error from 192.168.1.253:42762: remote error: tls: unknown certificate
2021/01/30 22:13:09 http: TLS handshake error from 192.168.1.253:40546: remote error: tls: unknown certificate
2021/01/30 22:13:09 Transport:http://music.163.com/eapi/abtest/group/get(music.163.com)(POST)
2021/01/30 22:13:09 http: TLS handshake error from 192.168.1.253:40558: remote error: tls: unknown certificate
2021/01/30 22:13:09 http: TLS handshake error from 192.168.1.253:40560: remote error: tls: unknown certificate
2021/01/30 22:13:09 http: TLS handshake error from 192.168.1.253:40562: remote error: tls: unknown certificate
2021/01/30 22:13:09 Transport:http://music.163.com/eapi/sp/flow/user/status(music.163.com)(POST)
2021/01/30 22:13:09 Transport:http://music.163.com/eapi/ad/loading/webviewlist(music.163.com)(POST)
2021/01/30 22:13:09 Transport:http://music.163.com/eapi/batch(music.163.com)(POST)
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:45516: remote error: tls: unknown certificate
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40582: remote error: tls: unknown certificate
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/batch(music.163.com)(POST)
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40588: remote error: tls: unknown certificate
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40590: remote error: tls: unknown certificate
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/cloudvideo/category/list(music.163.com)(POST)
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/garret/current/get(music.163.com)(POST)
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40604: remote error: tls: unknown certificate
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/song/enhance/privilege(music.163.com)(POST)
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40606: remote error: tls: unknown certificate
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/pl/count(music.163.com)(POST)
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40610: remote error: tls: unknown certificate
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/batch(music.163.com)(POST)
2021/01/30 22:13:10 http: TLS handshake error from 192.168.1.253:40612: remote error: tls: unknown certificate
2021/01/30 22:13:10 Transport:http://music.163.com/eapi/song/lyric?id=1338695683&cp=false&lv=7&tv=0&kv=0(music.163.com)(POST)
2021/01/30 22:13:29 http: TLS handshake error from 192.168.1.253:42844: remote error: tls: unknown certificate
2021/01/30 22:13:34 http: TLS handshake error from 192.168.1.253:37878: remote error: tls: unknown certificate
2021/01/30 22:13:34 Direct:http://clientlog.music.163.com/api/clientlog/upload?oc=e0061d8888fa6d84c29976afd032133c54ac82e273e299c85bdd42653449e77f37d6d931d0edbc82a108086b4df3203f(clientlog.music.163.com)(POST)
2021/01/30 22:13:35 http: TLS handshake error from 192.168.1.253:37882: remote error: tls: unknown certificate
2021/01/30 22:13:35 Transport:http://apm.music.163.com/api/clientlog/mam/upload?oc=e0061d8888fa6d84c29976afd032133c54ac82e273e299c85bdd42653449e77f37d6d931d0edbc82a108086b4df3203f(apm.music.163.com)(POST)
‘

**Comment by cnsilvan** [comment]
如果设置正确，信任证书尝试

测试机：android 11版本，可以使用

**Comment by cnsilvan** [comment]
再提一次，我一直强调不要使用网上公开的证书，请自己生成证书。

**Comment by phoenixxie7** [comment]
OK了
