### ISSUE TITLE
MacOS 运行只有Killed: 9

### ISSUE THREAD

**Issue by sifuluo** [cnsilvan/UnblockNeteaseMusic#41]
我直接下载的release，在Windows端工作良好，现在想在MacOS上运行，
但是运行./UnblockNeteaseMusic只会返回Killed:9
带上设置-h也是只有一样的返回信息，请问是什么问题呢？

**Comment by cnsilvan** [comment]
M1?

**Comment by sifuluo** [comment]
Intel，是一台mid2014的MacBook Pro

**Comment by cnsilvan** [comment]
尝试自己打包试一下
