### ISSUE TITLE
灰色歌曲能正常播放，已购买的专辑无法播放

### ISSUE THREAD

**Issue by aurorataro** [cnsilvan/UnblockNeteaseMusic#42]
环境：
网易云版本：Android 8.1.20
服务端版本：Golang 0.2.7
服务端环境：树莓派4B  Respbian buster版本
方式：手机wifi上网时，使用UnblockNeteaseMusic默认端口进行http代理
出现问题：灰色音乐可以正常播放，后台日志显示正常。播放已购买专辑时，无法播放.
无法播放的日志：https://paste.ubuntu.com/p/SzvHZ5CtZJ/
出现问题的歌曲截图：https://ftp.bmp.ovh/imgs/2021/02/41917da74cc7b729.jpg

**Comment by cnsilvan** [comment]
@aurorataro 尝试一下新版本
