### ISSUE TITLE
海外IP的音乐解锁

### ISSUE THREAD

**Issue by qy2009** [cnsilvan/UnblockNeteaseMusic#43]
Hi,

能够增加海外IP的音乐解锁嘛？ 我试了不同的音源都不行，基本上全是灰色的。谢谢啦

**Comment by cnsilvan** [comment]
按照现在这个情况，估计你只能自己搭国内代理了

**Comment by Izumiko** [comment]
@cnsilvan 你好，我在 [meng-chuan/Unlock-netease-cloud-music](https://github.com/meng-chuan/Unlock-netease-cloud-music) 的介绍里看到它通过添加`X-Real-IP` 来解锁海外限制，请问这个能否在本项目里实现呢？

**Comment by cnsilvan** [comment]
> @cnsilvan 你好，我在 [meng-chuan/Unlock-netease-cloud-music](https://github.com/meng-chuan/Unlock-netease-cloud-music) 的介绍里看到它通过添加`X-Real-IP` 来解锁海外限制，请问这个能否在本项目里实现呢？

你在国外用这个项目可以使用吗？

**Comment by Izumiko** [comment]
> 
> 
> > @cnsilvan 你好，我在 [meng-chuan/Unlock-netease-cloud-music](https://github.com/meng-chuan/Unlock-netease-cloud-music) 的介绍里看到它通过添加`X-Real-IP` 来解锁海外限制，请问这个能否在本项目里实现呢？
> 
> 你在国外用这个项目可以使用吗？

我现在在国内，是帮国外的朋友弄的，但她最近在准备考试，没空帮我测试了。。。
