### ISSUE TITLE
goruntime问题

### ISSUE THREAD

**Issue by hehe413** [cnsilvan/UnblockNeteaseMusic#44]
windows 下
通过参数 -o kuwo:kugou:migu 启动，发现每次只匹配其中一个平台的歌曲。查看源码后发现原因如下：
	for _, p := range providers {
		go utils.PanicWrapper(func() {
			ch <- calculateSongInfo(p.ParseSong(key))
		})
		sum++
	}
建议修改为
	for _, p := range providers {
		tmp_p := p
		go utils.PanicWrapper(func() {
			ch <- calculateSongInfo(tmp_p.ParseSong(key))
		})
		sum++
	}

**Comment by cnsilvan** [comment]
感谢反馈，不然我一定发现不了 这个经典错误，因为我平时就一个音源。已修复
