### ISSUE TITLE
我不太会用

### ISSUE THREAD

**Issue by xhd-come** [cnsilvan/UnblockNeteaseMusic#45]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.Windows10]
 - APP Version [e.g.7.0.22]
 - Version [e.g.0.2.8(arm5)]

**Smartphone (please complete the following information):**
 - APP Version [e.g.7.0.22]
 - Version [e.g.0.2.8(arm5)]

**Log**
Commit log

**Comment by xhd-come** [comment]
安卓的要用哪一个呢

**Comment by cnsilvan** [comment]
android需要你自行编译
