### ISSUE TITLE
IOS解锁问题

### ISSUE THREAD

**Issue by myleo1** [cnsilvan/UnblockNeteaseMusic#46]
网易云版本：8.10.6
UnblockNeteaseMusic-go版本：0.2.9
启动命令:$UnblockPath/UnblockNeteaseMusic -e -b -sl "3" -c $UnblockPath/server.crt -k $UnblockPath/server.key -l $UnblockPath/log.log -o "kuwo","kugou","migu" >/dev/null 2>&1 &
🚀使用http代理，填入ip和地址，没做其他改动

已签发证书，并且信任证书，在关于本机里也已打开，使用系统自带的代理也无果，请大佬指点是证书问题或是代理方式问题，感谢！！

log如下：
                 0.2.9  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic） 
2021/03/24 10:59:34 --------------------Config--------------------
2021/03/24 10:59:34 port= 80
2021/03/24 10:59:34 tlsPort= 443
2021/03/24 10:59:34 source= kuwo,kugou,migu
2021/03/24 10:59:34 certFile= /Users/leo/apps/UnblockNeteaseMusic-darwin-amd64/server.crt
2021/03/24 10:59:34 keyFile= /Users/leo/apps/UnblockNeteaseMusic-darwin-amd64/server.key
2021/03/24 10:59:34 logFile= /Users/leo/apps/UnblockNeteaseMusic-darwin-amd64/log.log
2021/03/24 10:59:34 mode= 1
2021/03/24 10:59:34 endPoint= true
2021/03/24 10:59:34 forceBestQuality= true
2021/03/24 10:59:34 searchLimit= 3
2021/03/24 10:59:34 -------------------Init Host-------------------
2021/03/24 10:59:34 Found UnblockNetEaseMusic Line
2021/03/24 10:59:34 HostDomain: map[interface.music.163.com:112.13.122.4 music.163.com:59.111.181.60]
2021/03/24 10:59:34 -------------------Init Proxy-------------------
2021/03/24 10:59:34 Http Proxy:
2021/03/24 10:59:34 fe80::1 , fe80::1c9f:d7ec:fa19:ff46 , fe80::dba4:fc4b:a5ac:70bc , fe80::ba1b:ae20:f7c0:ddaf , fe80::cb5d:a582:1d34:28d0 , 192.168.0.101 , fe80::74b4:a0ff:fe78:d87 , fe80::c417:c6cc:44c:8892 , fe80::a79f:9cdc:130c:115e , fe80::636b:7bbc:e42b:cc35
2021/03/24 10:59:34 starting Server  0.0.0.0:80
2021/03/24 10:59:34 starting TLS Server  0.0.0.0:443
2021/03/24 10:59:45 Received request CONNECT conf-darwin.xycdn.com 192.168.0.117:56440
2021/03/24 10:59:45 Received request CONNECT 112.13.122.4 192.168.0.117:56448
2021/03/24 10:59:45 Received request CONNECT 59.111.232.163 192.168.0.117:56442
2021/03/24 10:59:45 Received request CONNECT 112.13.122.4 192.168.0.117:56446
2021/03/24 10:59:45 Received request CONNECT firebaselogging-pa.googleapis.com 192.168.0.117:56450
2021/03/24 10:59:45 Received request CONNECT nstool.netease.com 192.168.0.117:56451
2021/03/24 10:59:45 Received request CONNECT 223.252.196.38 192.168.0.117:56458
2021/03/24 10:59:45 Received request CONNECT mam.netease.com 192.168.0.117:56452
2021/03/24 10:59:45 Received request CONNECT 223.252.196.38 192.168.0.117:56457
2021/03/24 10:59:45 Received request CONNECT 223.252.196.38 192.168.0.117:56456
2021/03/24 10:59:45 Received request CONNECT sdk1xyajs.data.p2cdn.com 192.168.0.117:56460
2021/03/24 10:59:45 Received request CONNECT 112.13.122.4 192.168.0.117:56464
2021/03/24 10:59:45 Received request CONNECT 112.13.122.4 192.168.0.117:56463
2021/03/24 10:59:45 Received request CONNECT only-795878-111-0-80-195.nstool.laiqukankan.com 192.168.0.117:56468
2021/03/24 10:59:45 Received request CONNECT 112.13.122.4 192.168.0.117:56470
2021/03/24 10:59:45 Received request CONNECT 112.13.122.4 192.168.0.117:56466
2021/03/24 10:59:46 Received request CONNECT 112.13.122.4 192.168.0.117:56472
2021/03/24 10:59:46 Received request CONNECT 112.13.122.4 192.168.0.117:56474
2021/03/24 10:59:46 Received request CONNECT 112.13.122.4 192.168.0.117:56476
2021/03/24 10:59:46 Received request CONNECT p4.music.126.net 192.168.0.117:56484
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56482
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56478
2021/03/24 10:59:46 Received request CONNECT p3.music.126.net 192.168.0.117:56488
2021/03/24 10:59:46 Received request CONNECT p4.music.126.net 192.168.0.117:56485
2021/03/24 10:59:46 Received request CONNECT p4.music.126.net 192.168.0.117:56487
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56492
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56490
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56494
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56496
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56498
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56500
2021/03/24 10:59:46 Received request CONNECT 112.13.122.4 192.168.0.117:56502
2021/03/24 10:59:46 Received request CONNECT 112.13.122.4 192.168.0.117:56504
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56506
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56508
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56510
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56516
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56512
2021/03/24 10:59:46 Received request CONNECT p1.music.126.net 192.168.0.117:56515
2021/03/24 10:59:46 Direct:http://iadmusicmat.music.126.net/ef6731c1c60f4f40ace447899cc30e47.jpg?imageView=1&type=webp&thumbnail=764y120(iadmusicmat.music.126.net)(GET)
2021/03/24 10:59:48 Received request CONNECT 112.13.122.4 192.168.0.117:56520
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56522
2021/03/24 10:59:49 Received request CONNECT p5.music.126.net 192.168.0.117:56524
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56526
2021/03/24 10:59:49 Received request CONNECT p5.music.126.net 192.168.0.117:56528
2021/03/24 10:59:49 Received request CONNECT p5.music.126.net 192.168.0.117:56531
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56532
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56534
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56536
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56540
2021/03/24 10:59:49 Received request CONNECT 112.13.122.4 192.168.0.117:56539
2021/03/24 10:59:50 Received request CONNECT p6.music.126.net 192.168.0.117:56542
2021/03/24 10:59:50 Received request CONNECT p3.music.126.net 192.168.0.117:56546
2021/03/24 10:59:50 Received request CONNECT p3.music.126.net 192.168.0.117:56547
2021/03/24 10:59:50 Received request CONNECT p3.music.126.net 192.168.0.117:56548
2021/03/24 10:59:50 Received request CONNECT 112.13.122.4 192.168.0.117:56550
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56557
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56556
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56559
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56561
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56560
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56562
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56564
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56567
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56568
2021/03/24 10:59:51 Received request CONNECT p2.music.126.net 192.168.0.117:56570
2021/03/24 10:59:51 Received request CONNECT 112.13.122.4 192.168.0.117:56572
2021/03/24 10:59:53 Received request CONNECT firebaselogging-pa.googleapis.com 192.168.0.117:56574
2021/03/24 10:59:53 Received request CONNECT 112.13.122.4 192.168.0.117:56576
2021/03/24 10:59:54 Received request CONNECT 112.13.122.4 192.168.0.117:56580
2021/03/24 10:59:54 Received request CONNECT 112.13.122.4 192.168.0.117:56579
2021/03/24 10:59:54 Received request CONNECT p1.music.126.net 192.168.0.117:56582
2021/03/24 10:59:54 Received request CONNECT p1.music.126.net 192.168.0.117:56588
2021/03/24 10:59:54 Received request CONNECT p1.music.126.net 192.168.0.117:56587
2021/03/24 10:59:54 Received request CONNECT p1.music.126.net 192.168.0.117:56589
2021/03/24 10:59:54 Received request CONNECT p1.music.126.net 192.168.0.117:56590
2021/03/24 10:59:55 Received request CONNECT p1.music.126.net 192.168.0.117:56592
2021/03/24 10:59:55 Received request CONNECT p1.music.126.net 192.168.0.117:56594
2021/03/24 10:59:56 Received request CONNECT lbs.netease.im 192.168.0.117:56598
2021/03/24 10:59:56 Received request CONNECT lbs.netease.im 192.168.0.117:56600
2021/03/24 10:59:56 Received request CONNECT wannos.127.net 192.168.0.117:56599
2021/03/24 10:59:56 Received request CONNECT 112.13.122.4 192.168.0.117:56607
2021/03/24 10:59:56 Received request CONNECT 112.13.122.4 192.168.0.117:56606
2021/03/24 10:59:56 Received request CONNECT 112.13.122.4 192.168.0.117:56608
2021/03/24 10:59:56 Received request CONNECT 112.13.122.4 192.168.0.117:56609
2021/03/24 10:59:56 Received request CONNECT 112.13.122.4 192.168.0.117:56610
2021/03/24 10:59:57 Received request CONNECT p2.music.126.net 192.168.0.117:56612

**Comment by myleo1** [comment]
貌似是ipv6的问题？server跑在mac上，请大佬们指点下，感谢！！

**Comment by cnsilvan** [comment]
没看见有价值的日志。我这里是正常的。
