### ISSUE TITLE
关于Android 高版本证书问题

### ISSUE THREAD

**Issue by cnsilvan** [cnsilvan/UnblockNeteaseMusic#48]
不能root的话，我的建议是自己打包 👉[apk-bot](https://github.com/cnsilvan/apk-bot)
有更好建议的，欢迎这里讨论

**Comment by flyhigherpi** [comment]
大佬咋弄

**Comment by cnsilvan** [comment]
> 大佬咋弄

没空弄，过几天多。自己打包apk 解决

**Comment by cnsilvan** [comment]
实在没空，有空再开
