### ISSUE TITLE
JAY【11月的肖邦】珊瑚海 kuwo匹配的

### ISSUE THREAD

**Issue by flyhigherpi** [cnsilvan/UnblockNeteaseMusic#51]
初听辣哭 了
再听笑了。
附上：http://ev.sycdn.kuwo.cn/45b4dc16234c8638a5b20a4c9ff3d290/60755529/resource/n1/95/86/1793951844.mp3
迷啊。那么多翻唱+原版的

**Comment by cnsilvan** [comment]
你是想提问题呢。还是嘲讽呢？

**Comment by flyhigherpi** [comment]
> 你是想提问题呢。还是嘲讽呢？

没有没有。忘了贴日志了。看看是咋回事。
2021/04/19 11:18:06 search song:飘移 周杰伦
2021/04/19 11:18:06 consumed: 786.309334ms
2021/04/19 11:18:06 {"Id":"185922","Size":28585874,"Br":999000,"Url":"http://other.player.rc03.sycdn.kuwo.cn/c5691d3ab1eb9013a1004b2b6bc42a54/607cf66e/resource/s3/42/65/1188351370.flac","Md5":"","Name":"飘移","Artist":"周杰伦","AlbumName":"十一月的萧邦","MatchScore":1,"Source":"kuwo"}
2021/04/19 11:18:19 Direct:http://clientlog.music.163.com/api/feedback/client/log(clientlog.music.163.com)(POST)
2021/04/19 11:18:19 Transport:http://apm.music.163.com/api/clientlog/mam/upload?oc=89ec1be3799083d2437d84b85556ca1c5bb0d4b2b23a34c11c38892e6e123fda33a649814e309366(apm.music.163.com)(POST)
2021/04/19 11:18:19 Transport:http://interface.music.163.com/eapi/song/enhance/player/url(interface.music.163.com)(POST)
2021/04/19 11:18:19 Transport:http://interface.music.163.com/eapi/song/lyric(interface.music.163.com)(POST)
2021/04/19 11:18:19 Direct:http://115.236.118.33/eapi/mlivestream/entrance/playpage/get(interface.music.163.com)(POST)
2021/04/19 11:18:19 find song info :{Quality:Lossless(3) Id:185920}
2021/04/19 11:18:19 search song:珊瑚海 周杰伦 梁心颐
2021/04/19 11:18:20 consumed: 616.986044ms
2021/04/19 11:18:20 {"Id":"185920","Size":3912642,"Br":128000,"Url":"http://ev.sycdn.kuwo.cn/7d84f54ca1143b28e325a901ebf28210/607cf67c/resource/n1/95/86/1793951844.mp3","Md5":"","Name":"珊瑚海","Artist":"周杰伦·梁心颐","AlbumName":"","MatchScore":0.96000004,"Source":"kuwo"}
2021/04/19 11:18:43 Transport:http://music.163.com/eapi/pccache/patch/get(music.163.com)(POST)
2021/04/19 11:18:44 Transport:http://music.163.com/eapi/pccache/patch/get(music.163.com)(POST)
2021/04/19 11:18:49 Direct:http://clientlog.music.163.com/api/feedback/client/log(clientlog.music.163.com)(POST)
漂移是匹配到了KUWO上的FLAC无损音源，就是这首珊瑚海试了好多次都是这首标准mp3。哈哈哈
然后就是翻唱的辣耳朵啊。辣啊。一起来听吧

**Comment by cnsilvan** [comment]
这个是因为 酷我 音源 本身有两首歌 名称&歌手一致。不过我已经优化了规则。应该解决了
