### ISSUE TITLE
听不了任何试听的歌曲了。

### ISSUE THREAD

**Issue by zhouxiaolong920** [cnsilvan/UnblockNeteaseMusic#55]
openwrt

UnblockNeteaseMusicGo_0.2.9-1_mipsel_24kc.ipk
luci-app-unblockmusic_2.3.5-9_all.ipk

log日志如下
root@OpenWrt:/tmp# cat unblockmusic.log
Sat, 24 Apr 2021 13:43:49 +0800 # Start UnblockNeteaseMusic
Sat, 24 Apr 2021 13:43:49 +0800 # UnblockNeteaseMusic Golang Version (http:5200, https:5201)
2021/04/24 05:43:50
        ##       ##         ##        ##   ##       ##       ## ##     ## ## ##      ## ##
        ##       ##       ## ##     ## ##  ##       ##    ##      ##      ##      ##      ##
        ##       ##      ##  ##    ##  ##  ##       ##   ##               ##     ##
        ##       ##     ##   ##   ##   ##  ##       ##    ## ## ##        ##     ##
        ##       ##    ##    ##  ##    ##  ##       ##            ##      ##     ##
        ##       ##   ##     ## ##     ##  ##       ##  ##        ##      ##      ##      ##
        ## ## ## ##  ##      ####      ##  ## ## ## ##   ## ## ##      ## ## ##    ## ## ##

                 0.2.9  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic）

2021/04/24 05:43:50 --------------------Config--------------------
2021/04/24 05:43:50 port= 5200
2021/04/24 05:43:50 tlsPort= 5201
2021/04/24 05:43:50 source= kuwo
2021/04/24 05:43:50 certFile= /usr/share/UnblockNeteaseMusicGo/server.crt
2021/04/24 05:43:50 keyFile= /usr/share/UnblockNeteaseMusicGo/server.key
2021/04/24 05:43:50 logFile=
2021/04/24 05:43:50 mode= 0
2021/04/24 05:43:50 endPoint= true
2021/04/24 05:43:50 forceBestQuality= true
2021/04/24 05:43:50 searchLimit= 0
2021/04/24 05:43:50 -------------------Init Host-------------------
2021/04/24 05:43:50 HostDomain: map[interface.music.163.com:101.71.154.241 music.163.com:59.111.181.35]
2021/04/24 05:43:50 -------------------Init Proxy-------------------
2021/04/24 05:43:50 Http Proxy:
2021/04/24 05:43:50 192.168.5.1 , 192.168.1.2 , fe80::52d2:f5ff:fe9b:cda9 , fdb3:23ae:a6ef::1 , fe80::52d2:f5ff:fe9b:cdaa
2021/04/24 05:43:50 starting Server  0.0.0.0:5200
2021/04/24 05:43:50 starting TLS Server  0.0.0.0:5201
2021/04/24 05:44:26 Transport:http://music.163.com/eapi/song/lyric(music.163.com)(POST)
2021/04/24 05:44:26 Direct:http://59.111.181.35/eapi/mlivestream/entrance/playpage/get(music.163.com)(POST)
2021/04/24 05:44:26 Transport:http://music.163.com/eapi/song/enhance/player/url(music.163.com)(POST)
2021/04/24 05:44:26 find song info :{Quality:Lossless(3) Id:27713963}
2021/04/24 05:44:26 search song:好心分手 卢巧音 王力宏
2021/04/24 05:44:27 consumed: 273.231754ms
2021/04/24 05:44:27 {"Id":"27713963","Size":0,"Br":0,"Url":"","Md5":"","Name":"","Artist":"","AlbumName":"","MatchScore":0,"Source":""}
2021/04/24 05:45:22 Direct:http://clientlog.music.163.com/api/feedback/client/log(clientlog.music.163.com)(POST)
2021/04/24 05:45:45 Transport:http://music.163.com/eapi/pl/count(music.163.com)(POST)
2021/04/24 05:47:45 Transport:http://music.163.com/eapi/pl/count(music.163.com)(POST)

只要是试听的。都返回"Size":0,"Br":0,"Url":"","Md5":"","Name":"","Artist":"","AlbumName":"","MatchScore":0,"Source":""}

运行参数：

 2122 root      1120 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 192.168.5.1:22 -p fdb3:23ae:a6ef::1:22 -K 300 -T 3
 2364 root      1612 S    /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -u /ubus -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -R -p 0.0.
 2430 root      1188 S    /usr/sbin/vsftpd -olisten_address=0.0.0.0 -olisten=YES -olisten_ipv6=NO /var/run/vsftpd/vsftpd.conf
 2931 root      1320 SN   /usr/sbin/nlbwmon -o /var/lib/nlbwmon -b 524288 -i 24h -r 30s -p /usr/share/nlbwmon/protocols -G 10 -I 1
 2964 root       948 S    /usr/bin/vlmcsd -i /etc/vlmcsd.ini -L 0.0.0.0:1688
 3118 root      1236 S<   /usr/sbin/ntpd -n -N -S /usr/sbin/ntpd-hotplug -p ntp1.aliyun.com -p time1.cloud.tencent.com -p time.ustc
 3979 root      1180 R    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 192.168.5.1:22 -p fdb3:23ae:a6ef::1:22 -K 300 -T 3
22125 dnsmasq   1368 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c -k -x /var/run/dnsmasq/dnsmasq.cfg01411c.pid
22409 root         0 IW   [kworker/0:5]
22602 root      1248 S    /bin/sh /usr/share/openclash/openclash_watchdog.sh
24705 root      1232 S    /usr/sbin/crond -f -c /etc/crontabs -l 5
24711 root      654m S    UnblockNeteaseMusic -b -p 5200 -sp 5201 -m 0 -c /usr/share/UnblockNeteaseMusicGo/server.crt -k /usr/share
24848 root      1232 S    /bin/sh /usr/share/UnblockNeteaseMusic/logcheck.sh
24986 root      1232 S    sleep 29s
25018 root      1232 S    sleep 60

**Comment by paceyuan** [comment]
版本一样，同样的问题，我的有这个错误
2021/04/25 00:01:31 http: TLS handshake error from 客户端ip:端口号: EOF

**Comment by jqyisbest** [comment]
隔壁NodeJS版本有大佬发现[酷我改了查询API返回的数据导致解析出错](https://github.com/nondanee/UnblockNeteaseMusic/issues/737#issuecomment-826024311)，我猜Golang版应该也中枪了..

**Comment by flyhigherpi** [comment]
现在音源除了酷狗已经全线阵亡。
酷狗的匹配效果惨不忍睹。
真不如酷我

**Comment by chenjuncheng** [comment]
把kuwo.go的SearchSong方法

rid, ok := kowoSong["rid"].(json.Number) 的 json.Number 
改为：
rid, ok := kowoSong["rid"].(string)
就可以了。

应该是kuwo的json格式改了，把rid从数字变成字符串了

**Comment by zhouxiaolong920** [comment]
> 把kuwo.go的SearchSong方法
> 
> rid, ok := kowoSong["rid"].(json.Number) 的 json.Number
> 改为：
> rid, ok := kowoSong["rid"].(string)
> 就可以了。
> 
> 应该是kuwo的json格式改了，把rid从数字变成字符串了

兄弟给力。。

**Comment by paceyuan** [comment]
> 把kuwo.go的SearchSong方法
> 
> rid, ok := kowoSong["rid"].(json.Number) 的 json.Number
> 改为：
> rid, ok := kowoSong["rid"].(string)
> 就可以了。
> 
> 应该是kuwo的json格式改了，把rid从数字变成字符串了

请问在哪修改这个参数？谢谢

**Comment by 4860575** [comment]
> 把kuwo.go的SearchSong方法
> 
> rid, ok := kowoSong["rid"].(json.Number) 的 json.Number
> 改为：
> rid, ok := kowoSong["rid"].(string)
> 就可以了。
> 
> 应该是kuwo的json格式改了，把rid从数字变成字符串了

修改后编译错误：
Building...
# github.com/cnsilvan/UnblockNeteaseMusic/provider/kuwo
provider/kuwo/kuwo.go:5:2: imported and not used: "encoding/json"
provider/kuwo/kuwo.go:73:52: rid.String undefined (type string has no field or method String)
provider/kuwo/kuwo.go:75:26: rid.String undefined (type string has no field or method String)
--------------------------------------------
Version: 0.2.9
Git commit: 6a516f8
Go version: go version go1.16.3 linux/amd64
Build Time: 2021-04-25 14:12:33
Build Finish
