### ISSUE TITLE
[BUG][OpenWRT]Recover panic :  music.163.com ip:127.0.0.1 is error

### ISSUE THREAD

**Issue by Luupw3d** [cnsilvan/UnblockNeteaseMusic#62]
**Describe the bug**
Application failed to start.

**Log**
                 0.2.11  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic） 

2021/06/13 19:56:49 --------------------Config--------------------
2021/06/13 19:56:49 port= 5210
2021/06/13 19:56:49 tlsPort= 5211
2021/06/13 19:56:49 source= kuwo
2021/06/13 19:56:49 certFile= /usr/share/UnblockNeteaseMusic/server.crt
2021/06/13 19:56:49 keyFile= /usr/share/UnblockNeteaseMusic/server.key
2021/06/13 19:56:49 logFile= /tmp/unblockneteasemusic.log
2021/06/13 19:56:49 mode= 0
2021/06/13 19:56:49 endPoint= false
2021/06/13 19:56:49 forceBestQuality= false
2021/06/13 19:56:49 searchLimit= 0
2021/06/13 19:56:49 -------------------Init Host-------------------
2021/06/13 19:56:49 Recover panic :  music.163.com ip:127.0.0.1 is error
ping6 bad address,please check IPv6 DNS forwards.if IPv6 DNS forwards is enabled, please restart
Sun, 13 Jun 2021 19:57:00 +0800 try restart...

**Comment by goodtogood** [comment]
same problem

**Comment by catsimple** [comment]
cat /dev/null > /etc/hosts
service dnsmasq restart
sleep 10s
然后就可以正常执行了

**Comment by Luupw3d** [comment]
清空Hosts并重启Dnsmasq吗？我尝试一下，感谢您的回复！

**Comment by Luupw3d** [comment]
> `cat /dev/null > /etc/hosts` `service dnsmasq restart` `sleep 10s` 然后就可以正常执行了

清空Hosts并重启Dnsmasq吗？我尝试一下，感谢您的回复！

**Comment by seven4x** [comment]
遇到了同样的问题，感谢
