### ISSUE TITLE
在openwrt下执行会提示Recover panic然后程序自动退出

### ISSUE THREAD

**Issue by catsimple** [cnsilvan/UnblockNeteaseMusic#74]
https://github.com/cnsilvan/UnblockNeteaseMusic/issues/62#issue-919783740
日志和上边的一样，遂发现/etc/hosts里有两行将music.163.com指向127.0.0.1的代码
清空hosts后，重启dnsmasq，程序正常运行，请问这是什么情况呢

**Comment by cnsilvan** [comment]
host模式会修改本地host的.

**Comment by catsimple** [comment]
程序有点问题，看到程序会备份hosts且退出后恢复hosts的代码，但是有时候程序panic了以后，就无法执行恢复hosts的代码了。建议在启动前检查hosts是否恢复了备份，不然就会遇到这个尴尬的问题。

我只当服务端用，所以把修改本地hosts的代码删了就可以了
`func appendToHost(hostPath string) error {
	content := " \n# UnblockNetEaseMusic（Go）\n"
	for domain, _ := range common.HostDomain {
		content += common.ProxyIp + " " + domain + "\n"
	}
	return appendToFile(hostPath, content)
}`
