### ISSUE TITLE
网易云音乐golang版出现错误无法解锁

### ISSUE THREAD

**Issue by yinzhefuyun** [cnsilvan/UnblockNeteaseMusic#8]
解锁网易云音乐golang版出问题，初步感觉是拼接url字符串的时候拼接错误，下面的链接出现了http://music.163.comhttp// 这样的奇怪域名链接

详细日志
A：search song:说好不哭 周杰伦
{"Id":"1391274164","Size":43879571,"Br":999000,"Url":"http://su.sycdn.kuwo.cn/ca5bada1ac976bebc23dd6c5eaf991e5/5e624f97/resource/s1/93/41/1323319837.flac","Md5":"","Name":"说好不哭 (with 五月天阿信)","Artist":"周杰伦","MatchScore":0.6057143}
http.Client.Do fail:Get "http://music.163.comhttp//su.sycdn.kuwo.cn/ca5bada1ac976bebc23dd6c5eaf991e5/5e624f97/resource/s1/93/41/1323319837.flac": dial tcp: lookup music.163.comhttp on 127.0.0.1:53: no such host
Received request CONNECT m8.music.126.net 192.168.1.243:3727
find song info,id: 1391274164
hit cache:

程序编译在lean的固件中，选择酷我的音源

**Comment by cnsilvan** [comment]
ok，发现是代理模式下不兼容。

**Comment by cnsilvan** [comment]
已修复
