### ISSUE TITLE
网络连接错误问题

### ISSUE THREAD

**Issue by WROIATE** [cnsilvan/UnblockNeteaseMusic#81]
**Describe the bug**
目前编译的版本为`bbd409061c4ac36015df6c4bce3daa5bab22c3da`
当前版本存在打开网易云出现网络连接失败、无法查看用户信息等问题
**Screenshots**
![image](https://user-images.githubusercontent.com/44677306/169993224-405b7a01-15c6-4e77-b575-4809af208691.png)

**Desktop (please complete the following information):**
 - OS: Windows10

**Comment by WROIATE** [comment]
![image](https://user-images.githubusercontent.com/44677306/170418782-d0162a4b-80e3-4818-8e58-a90ae4c9bd25.png)
日志大概是这个样子

**Comment by WROIATE** [comment]
找到原因，是因为证书设置错误

**Comment by WROIATE** [comment]
貌似现在windows也需要强制https了

**Comment by yaocl0** [comment]
怎么解决的？
