### ISSUE TITLE
当使用默认音源和-e参数后ios部分仍然不正常

### ISSUE THREAD

**Issue by paldier** [cnsilvan/UnblockNeteaseMusic#9]
如果使用默认音源，部分歌曲会报如下错误，其他歌曲又不会
2020/03/09 04:11:46 http: TLS handshake error from 192.168.50.134:53101: EOF
2020/03/09 04:11:47 http: TLS handshake error from 192.168.50.134:53104: EOF
2020/03/09 04:11:48 http: TLS handshake error from 192.168.50.134:53108: EOF
2020/03/09 04:11:49 http: TLS handshake error from 192.168.50.134:53109: EOF
2020/03/09 04:11:50 http: TLS handshake error from 192.168.50.134:53112: EOF
2020/03/09 04:11:51 http: TLS handshake error from 192.168.50.134:53113: EOF
，而如果只使用kugou音源这时候ios完全正常，其他win和linux都没这个问题

**Comment by cnsilvan** [comment]
信任证书了吗？歌曲是？ios端提示什么？

**Comment by paldier** [comment]
肯定信任过了，大部分都是正常的，只有极个别不能播放或者不能下载，但使用kugou时又正常

**Comment by paldier** [comment]
更正：前面说的应该是kuwo

**Comment by cnsilvan** [comment]
你要具体说一下哪一首歌

**Comment by paldier** [comment]
コラージュ (WEB动画《卫宫家今天的饭》片尾曲 ； WEBアニメ「衛宮さんちの今日のごはん」EDテーマ)

**Comment by cnsilvan** [comment]
kuwo本来就没有这首歌的音源。任何平台没有歌曲都会播放失败。

**Comment by paldier** [comment]
有啊，我不是说了win和linux都正常，唯独ios使用默认音源的时候不能播放

**Comment by cnsilvan** [comment]
发一下日志，搜索歌曲后的日志

**Comment by paldier** [comment]
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=676e412b8971ecdf1323f1486a04dcd3c8e2edcd25e1af3ac19b9bf0620b3cbd537be1db312a0bd56d57bfe2faa31492dfadfc3522452cd3bf122d59fa1ed6a2&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/zone/songplay/entry/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/search/localsong/upload?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/mlog/songplay/entrance?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/player/url/v1?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/privilege?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music/dislike/get?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 04:03:34 http: TLS handshake error from 192.168.50.97:54624: EOF
Transport:http://interface.music.163.com/eapi/music/dislike/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/like/get?_nmclfl=1(interface.music.163.com)(POST)
find song info,id: 543611431
search song:コラージュ 三月のパンタシア
Transport:http://interface.music.163.com/eapi/user/pretend/info?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/user/playlist/song/category/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/user/playlist/consume/notice/refresh?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/homepage/miniprogram/entrance/list?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/homepage/miniprogram/fm/preview?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=676e412b8971ecdf1323f1486a04dcd3c8e2edcd25e1af3ac19b9bf0620b3cbd537be1db312a0bd56d57bfe2faa31492dfadfc3522452cd3bf122d59fa1ed6a2&_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/personalized/playlist/recommend?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/sub/artist/new/works/entrance?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/lyric?_nmclfl=1(interface.music.163.com)(POST)
Transport:https://interface.music.163.com/eapi/sp/flow/addr/v2?_nmclfl=1(interface.music.163.com)(POST)
Transport:https://interface.music.163.com/eapi/weixin/config?_nmclfl=1(interface.music.163.com)(POST)
Transport:https://music.163.com/eapi/resource/new/user/get?_nmclfl=1(music.163.com)(POST)
2020/03/10 04:03:35 http: TLS handshake error from 192.168.50.97:54626: EOF
consumed: 1007 ms
{"Id":"543611431","Size":4306069,"Br":128000,"Url":"http://fs.android2.kugou.com/fd696db2e74a818b85a9efccdd227c89/5e671197/G125/M0A/0E/0D/XZQEAFqfuCqADxyTAEG0lTjPvHU167.mp3","Md5":"","Name":"コラージュ","Artist":"三月のパンタシア","MatchScore":1}
Transport:http://interface.music.163.com/eapi/v6/playlist/detail?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/v3/song/detail?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 04:03:36 http: TLS handshake error from 192.168.50.97:54629: EOF
Transport:https://music.163.com/eapi/resource/rcmd/daily/get?_nmclfl=1(music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/feedback/weblog/fastlog?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/mlog/songplay/entrance?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/zone/songplay/entry/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/song/enhance/player/url/v1?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/playlist/update/playcount?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 04:03:37 http: TLS handshake error from 192.168.50.97:54630: EOF
find song info,id: 543611431
hit cache: {"Id":"543611431","Size":4306069,"Br":128000,"Url":"http://fs.android2.kugou.com/fd696db2e74a818b85a9efccdd227c89/5e671197/G125/M0A/0E/0D/XZQEAFqfuCqADxyTAEG0lTjPvHU167.mp3","Md5":"f27a23fd5b1c97ad7ddbfb5ab3e3c025","Name":"コラージュ","Artist":"三月のパンタシア","MatchScore":1}
Transport:http://interface.music.163.com/eapi/batch?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://interface.music.163.com/eapi/music/songshare/text/recommend/get?_nmclfl=1(interface.music.163.com)(POST)
Transport:http://music.163.com/api/feedback/client/log?MUSIC_U=676e412b8971ecdf1323f1486a04dcd3c8e2edcd25e1af3ac19b9bf0620b3cbd537be1db312a0bd56d57bfe2faa31492dfadfc3522452cd3bf122d59fa1ed6a2&_nmclfl=1(music.163.com)(POST)
Direct:http://115.236.118.33/eapi/mlivestream/entrance/playpage/v5/get?_nmclfl=1(interface.music.163.com)(POST)
2020/03/10 04:03:38 http: TLS handshake error from 192.168.50.97:54632: EOF
2020/03/10 04:03:39 http: TLS handshake error from 192.168.50.97:54635: EOF
2020/03/10 04:03:39 http: TLS handshake error from 192.168.50.97:54638: EOF
2020/03/10 04:03:40 http: TLS handshake error from 192.168.50.97:54642: EOF
2020/03/10 04:03:41 http: TLS handshake error from 192.168.50.97:54643: EOF
2020/03/10 04:03:42 http: TLS handshake error from 192.168.50.97:54644: EOF
2020/03/10 04:03:43 http: TLS handshake error from 192.168.50.97:54645: EOF
2020/03/10 04:03:44 http: TLS handshake error from 192.168.50.97:54646: EOF
2020/03/10 04:03:45 http: TLS handshake error from 192.168.50.97:54647: EOF
2020/03/10 04:03:46 http: TLS handshake error from 192.168.50.97:54648: EOF
这个是kugou有的，这就是为什么一开始我说的kugou，然后其他的是kuwo有

**Comment by cnsilvan** [comment]
我看你的问题描述有点懵
第一：默认音源是什么音源（luci的默认音源是kuwo，这里是kuwo:kugou）？启动日志里面有；
第二：我尝试 kuwo单音源是没有这首歌的；

**Comment by paldier** [comment]
--------------------Config--------------------
port= 5200
tlsPort= 5300
source= kuwo:kugou
certFile= /jffs/softcenter/bin/Music/server.crt
keyFile= /jffs/softcenter/bin/Music/server.key
mode= 0
endPoint= true

**Comment by cnsilvan** [comment]
网易云版本是？是否升级了最新版本。

**Comment by paldier** [comment]
最新版

**Comment by cnsilvan** [comment]
ok 发现7.0.20版本 无法使用。

**Comment by cnsilvan** [comment]
[0.2.0](https://github.com/cnsilvan/UnblockNeteaseMusic/releases/tag/0.2.0)已修复kugou，其他源正常
